# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gadgetfreak_web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('img1', models.ImageField(upload_to=gadgetfreak_web.models.image1_path)),
                ('img2', models.ImageField(upload_to=gadgetfreak_web.models.image2_path)),
                ('img3', models.ImageField(upload_to=gadgetfreak_web.models.image3_path)),
                ('img4', models.ImageField(upload_to=gadgetfreak_web.models.image4_path)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
