# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import gadgetfreak_web.models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgetfreak_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='img1',
            new_name='img_1',
        ),
        migrations.RemoveField(
            model_name='device',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='device',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='device',
            name='img4',
        ),
        migrations.AddField(
            model_name='device',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to=gadgetfreak_web.models.image2_path),
        ),
        migrations.AddField(
            model_name='device',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to=gadgetfreak_web.models.image3_path),
        ),
        migrations.AddField(
            model_name='device',
            name='img_4',
            field=models.ImageField(blank=True, null=True, upload_to=gadgetfreak_web.models.image4_path),
        ),
        migrations.AddField(
            model_name='device',
            name='img_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=gadgetfreak_web.models.image_thumb_path),
        ),
        migrations.AddField(
            model_name='device',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
