# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gadgetfreak_web', '0002_auto_20170105_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gadgetfreak_web.Device')),
            ],
        ),
    ]
