# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gadgetfreak_web.models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgetfreak_web', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('topic_type', models.CharField(choices=[('R', 'Review'), ('C', 'Comment')], max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to=gadgetfreak_web.models.topic_img_path)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('contents', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gadgetfreak_web.Device')),
            ],
        ),
    ]
