# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 17:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gadgetfreak_web', '0006_auto_20170109_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
